FROM python:3.10

RUN mkdir /harvester_bot
WORKDIR /harvester_bot

COPY requirements.txt .
COPY tg_bot /harvester_bot/tg_bot

RUN apt-get update && apt-get install -y postgresql-client
RUN pip install -r requirements.txt

RUN chmod a+x /harvester_bot/tg_bot/app.sh
CMD /harvester_bot/tg_bot/app.sh